age = [74 69 63 63 69 57 58 NaN 83 81 63 74 63 52 75 62 71 69 73 76 85 79 77 69 52]';
labels = categorical(["control" "control" "control" "control" "control" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD" "PD"]');
sex = categorical(["F" "F" "M" "M" "F" "M" "M" "M" "M" "M" "M" "M" "F" "M" "F" "F" "M" "F" "F" "F" "M" "F" "M" "F" "M"]');
fprintf('Control group (n=%d): [median age %d yr (range %d–%d), %d females, %d males] \n',...
    sum(labels=="control"), nanmedian(age(labels=="control")), min(age(labels=="control")), max(age(labels=="control")), ...
    sum(sex(labels=="control")=="F"), sum(sex(labels=="control")=="M"));
fprintf('PD group (n=%d): [median age %d yr (range %d–%d), %d females, %d males] \n',...
    sum(labels=="PD"), nanmedian(age(labels=="PD")), min(age(labels=="PD")), max(age(labels=="PD")), ...
    sum(sex(labels=="PD")=="F"), sum(sex(labels=="PD")=="M"));